name: Build and Test

on:
  push:
    branches: 
      - master

jobs: 
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: ls
      run: ls
    - name: configure
      run: sudo apt-get install python libglu1-mesa-dev libxrandr-dev libxi-dev
    - name: premake      
      run: ./tools/premake5/linux64/premake5 gmake
    - name: make
      run: make -j config=release_x64
    - name: Upload Binary
      uses: actions/upload-artifact@v2
      with:
        name: Binary_${{ github.run_number }}
        path: ./dist/bin/Release/*


  run-unit-test:
    runs-on: ubuntu-latest
    needs: build-linux
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v2
      with:
        name: Binary_${{ github.run_number }}
        path: ./
    - name: chmod
      run: chmod +x ./x64
    - name: unit test
      run: ./x64 --gtest_output=xml:./result.xml
    - name: Upload Unit Test Results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: UnitTestResults_${{ github.run_number }}
        path: result.xml        
  
  run-unit-test1:
    runs-on: ubuntu-latest
    needs: build-linux
    strategy:
      matrix:
        commands: ["./x64 --gtest_filter=*test0 --gtest_output=xml:./result.xml", "./x64 --gtest_filter=*test1 --gtest_output=xml:./result.xml"]
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v2
      with:
        name: Binary_${{ github.run_number }}
        path: ./
    - name: chmod
      run: chmod +x ./x64
    - name: unit test
      run: ${{ matrix.commands }}
    - name: Upload Unit Test Results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: UnitTestResults1_${{ github.run_number }}
        path: result.xml        
  
  publish-results:
    runs-on: ubuntu-latest
    needs: [run-unit-test, run-unit-test1]
    if: success() || failure()
    
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v2
      with:
        name: UnitTestResults_${{ github.run_number }}
        path: ./
    - name: Download Artifacts1
      uses: actions/download-artifact@v2
      with:
        name: UnitTestResults1_${{ github.run_number }}
        path: ./  
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1.6
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        files: ./*.xml

