name: Build and Test

on:
  push:
    branches: 
      - master

jobs: 
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: ls
      run: ls
    - name: configure
      run: sudo apt-get install python libglu1-mesa-dev libxrandr-dev libxi-dev
    - name: premake      
      run: ./tools/premake5/linux64/premake5 gmake
    - name: make
      run: make -j config=release_x64
    - name: unit test
      run: ./dist/bin/Release/x64 --gtest_output=xml:./result.xml
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1.6
      if: always()
      with:
        github_token: ${{ secrets.PUBLIC_ACCESS_TOKEN }}
        files: result.xml
